environments:
  Labs:
    pipelines:
      - leave-ecuador-front
pipelines:
  leave-ecuador-front:
    group: testear
    materials:
      git_material:
        branch: master
        git: "https://github.com/scrodrig/test-react-gocd.git"
    stages:
      - hawkeye:
          jobs:
            build:
              tasks:
                - exec:
                  arguments:
                    - "-c"
                    - "docker run --rm -v $PWD:/target stono/hawkeye"
                  command: /bin/bash
      - test:
          jobs:
            build:
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "npm install && CI=true npm test"
                    command: /bin/bash
