environments:
  Labs:
    pipelines:
      - leave-ecuador-backend
pipelines:
  leave-ecuador-backend:
    group: labs-leave-ec
    materials:
      git_material:
        branch: master
        git: "https://github.com/scrodrig/test-react-gocd.git"
    stages:
      - test:
          jobs:
            build:
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "npm install"
                      - "npm test -ci=true"
                    command: /bin/bash
