environments:
  Labs:
    pipelines:
      - leave-ecuador-front
pipelines:
  leave-ecuador-front:
    group: algo-que-test
    materials:
      git_material:
        branch: master
        git: "https://github.com/scrodrig/test-react-gocd.git"
    stages:
      - test:
          jobs:
            build:
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "CI=true npm test"
                    command: /bin/bash
